Repository matheusberger/pb-ios, pull requests merged in 2023-12, with the labels that each got.

#12 Feature/song detail
  PedalBoard.xcodeproj/project.pbxproj
  PedalBoard/Assets.xcassets/PedalBoardColors/Contents.json
  PedalBoard/Assets.xcassets/PedalBoardColors/PedalBoardPurple.colorset/Contents.json
  PedalBoard/Assets.xcassets/PedalBoardColors/PedalBoardYellow.colorset/Contents.json
  PedalBoard/PedalBoardApp.swift
  PedalCore/Models/Pedal/Pedal+Populate.swift
  PedalCore/Models/Song/Song+Populate.swift
  PedalCore/Models/Song/Song.swift
  PedalCore/Protocols/AddSongDelegate.swift
  PedalCore/Protocols/PedalServiceProtocol.swift
  PedalCore/ViewModels/Songs/CreateSongViewModel.swift
  PedalCore/ViewModels/Songs/SongDetailViewModel.swift
  PedalCore/ViewModels/Songs/SongsListViewModel.swift
  PedalCore/Views/Components/KnobView.swift
  PedalCore/Views/Components/KnobViewStyle.swift
  PedalCore/Views/Components/KnobsGridView.swift
  PedalCore/Views/Songs/CreateSong/CreateSongView.swift
  PedalCore/Views/Songs/SelectPedal/SelectPedalRow.swift
  PedalCore/Views/Songs/SelectPedal/SelectPedalView.swift
  PedalCore/Views/Songs/SongDetail/SongDetailView.swift
  PedalCore/Views/Songs/SongDetailView.swift
  PedalCore/Views/Songs/SongList/SongListRow.swift
  PedalCore/Views/Songs/SongList/SongsListView.swift
  PedalCoreTests/Mock/AddsongDelegateMock.swift
  PedalCoreTests/ViewModels/CreateSongViewModelTests.swift
  PedalCoreTests/ViewModels/SongDetailViewModelTests.swift
  PedalCoreTests/ViewModels/SongsViewModelTests.swift
Labels: enhancement

#13 Created the persistence layer using Json, with Pedal and Song providers
  PedalBoard.xcodeproj/project.pbxproj
  PedalBoard/PedalBoardApp.swift
  PedalCore/Models/Pedal/Knob.swift
  PedalCore/Models/Pedal/Pedal.swift
  PedalCore/Models/Song/Song.swift
  PedalCore/Providers/DataProviderProtocol.swift
  PedalCore/Providers/LocalDataProvider.swift
  PedalCore/Services/JsonDataService.swift
  PedalCore/Services/PersistenceProtocol.swift
  PedalCore/ViewModels/Songs/SongsListViewModel.swift
  PedalCore/Views/Songs/SongList/SongsListView.swift
  PedalCoreTests/Mock/MockPersistanceService.swift
  PedalCoreTests/Providers/LocalDataProviderTests.swift
  PedalCoreTests/Services/JsonDataServiceTests.swift
  PedalCoreTests/ViewModels/SongsViewModelTests.swift
Labels: enhancement

#16 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#19 populate buttons removed
  PedalCore/Views/HomeView.swift
  PedalCore/Views/Songs/SongList/SongsListView.swift
Labels: enhancement

#18 bottom padding added
  PedalCore/Views/Songs/SongList/SongsListView.swift
Labels: bug

#17 Async save/load functions in JsonDataService
  PedalCore/Providers/DataProviderProtocol.swift
  PedalCore/Providers/LocalDataProvider.swift
  PedalCore/Services/JsonDataService.swift
  PedalCore/Services/PersistenceProtocol.swift
  PedalCore/ViewModels/Songs/SongsListViewModel.swift
  PedalCoreTests/Mock/MockPersistanceService.swift
Labels: enhancement
